### ISSUE TITLE
Help needed to account for density compensation 

### ISSUE THREAD

**Issue by hkaggarwal** [guanhuaw/Bjork#1]
Hello @guanhuaw,

Thank you for the codes. 

I am struggling with following two issues. It will be great if you could please help me with these. 

1. Does the current A.H (adjoint of the forward model) operator account for density compensation factor as well? If yes, please let me know. If no, can I use TorchKBNufft's  tkbn.calc_density_compensation_function. But, I am not sure if gradients will propagate properly or not. Can you please let me know how to account for density compensation in your code. 

2. If I create two operators as follows:
A= NuSense_om(smaps, traj)
AHA=NuSenseFrame_om(smaps, traj)
z1=A.H * (A* img)
z2=AHA*img

Then range of z1, and z2 are very different. The values in z2 are very high, it seems to have some different normalization. How can I normalize AHA so that both z1 and z2 are same?

Any suggestions will be helpful. 

Thank you,
Hemant

**Comment by guanhuaw** [comment]
Hi @hkaggarwal ,

1. We did not use the DCF for the initialization, instead, we adopted the QPLS (as can be seen in the Bjork paper). 
2. There are some inconsistencies in the torchkbnufft package. I will submit a pull request to the torchkbnufft repo.

Thanks much for your attention!

Best,
Guanhua
